language: php

php:
  - 7.1
  - 7.2
env:
  - SYMFONY_VERSION=origin/master

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: ./vendor/bin/phpunit --configuration phpunit.travis.xml
